name: Sync translations

on:
  workflow_dispatch:
  schedule:
    # Time 10:44 was chosen at random to avoid periods of high load.
    - cron: "44 10 * * WED,SAT"

concurrency:
  group: "sync-translations"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  sync-translations:
    runs-on: ubuntu-latest

    if: ${{ github.repository == 'Nitro-Bolt/extensions' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: master
          token: "${{ secrets.AUTOMATION }}"
          persist-credentials: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Upload source strings
        run: pnpm run upload-translations
        env:
          TRANSIFEX_TOKEN: "${{ secrets.TRANSIFEX }}"
          TRANSIFEX_ORGANIZATION: "nitrobolt"
          TRANSIFEX_PROJECT: "nitrobolt"
          TRANSIFEX_RUNTIME_RESOURCE: "extension-runtime"
          TRANSIFEX_METADATA_RESOURCE: "extension-metadata"
      - name: Download translations
        run: pnpm run download-translations
        env:
          TRANSIFEX_TOKEN: "${{ secrets.TRANSIFEX }}"
          TRANSIFEX_ORGANIZATION: "nitrobolt"
          TRANSIFEX_PROJECT: "nitrobolt"
          TRANSIFEX_RUNTIME_RESOURCE: "extension-runtime"
          TRANSIFEX_METADATA_RESOURCE: "extension-metadata"
      - name: Commit and push updates
        run: |
          if [[ ! $(git status --porcelain -- translations/extension-runtime.json translations/extension-metadata.json download-warnings.txt) ]]; then
            echo "No translation updates."
            exit 0
          fi
          git add translations/extension-runtime.json translations/extension-metadata.json download-warnings.txt
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git commit -m "chore: update translations"
          git pull --rebase origin master
          git push origin master
